// Code generated by protoc-gen-go-register. DO NOT EDIT.
// Sources: alert.proto, details.proto

package pb

import (
	transport "github.com/erda-project/erda-infra/pkg/transport"
	reflect "reflect"
)

// RegisterAlertServiceImp alert.proto
func RegisterAlertServiceImp(regester transport.Register, srv AlertServiceServer, opts ...transport.ServiceOption) {
	_ops := transport.DefaultServiceOptions()
	for _, op := range opts {
		op(_ops)
	}
	RegisterAlertServiceHandler(regester, AlertServiceHandler(srv), _ops.HTTP...)
	RegisterAlertServiceServer(regester, srv, _ops.GRPC...)
}

// RegisterAlertDetailServiceImp details.proto
func RegisterAlertDetailServiceImp(regester transport.Register, srv AlertDetailServiceServer, opts ...transport.ServiceOption) {
	_ops := transport.DefaultServiceOptions()
	for _, op := range opts {
		op(_ops)
	}
	RegisterAlertDetailServiceHandler(regester, AlertDetailServiceHandler(srv), _ops.HTTP...)
	RegisterAlertDetailServiceServer(regester, srv, _ops.GRPC...)
}

// ServiceNames return all service names
func ServiceNames(svr ...string) []string {
	return append(svr,
		"erda.core.monitor.alert.AlertDetailService",
		"erda.core.monitor.alert.AlertService",
	)
}

var (
	alertServiceClientType  = reflect.TypeOf((*AlertServiceClient)(nil)).Elem()
	alertServiceServerType  = reflect.TypeOf((*AlertServiceServer)(nil)).Elem()
	alertServiceHandlerType = reflect.TypeOf((*AlertServiceHandler)(nil)).Elem()

	alertDetailServiceClientType  = reflect.TypeOf((*AlertDetailServiceClient)(nil)).Elem()
	alertDetailServiceServerType  = reflect.TypeOf((*AlertDetailServiceServer)(nil)).Elem()
	alertDetailServiceHandlerType = reflect.TypeOf((*AlertDetailServiceHandler)(nil)).Elem()
)

// AlertServiceClientType .
func AlertServiceClientType() reflect.Type { return alertServiceClientType }

// AlertServiceServerType .
func AlertServiceServerType() reflect.Type { return alertServiceServerType }

// AlertServiceHandlerType .
func AlertServiceHandlerType() reflect.Type { return alertServiceHandlerType }

// AlertDetailServiceClientType .
func AlertDetailServiceClientType() reflect.Type { return alertDetailServiceClientType }

// AlertDetailServiceServerType .
func AlertDetailServiceServerType() reflect.Type { return alertDetailServiceServerType }

// AlertDetailServiceHandlerType .
func AlertDetailServiceHandlerType() reflect.Type { return alertDetailServiceHandlerType }

func Types() []reflect.Type {
	return []reflect.Type{
		// client types
		alertServiceClientType,
		alertDetailServiceClientType,
		// server types
		alertServiceServerType,
		alertDetailServiceServerType,
		// handler types
		alertServiceHandlerType,
		alertDetailServiceHandlerType,
	}
}
